name: Build

on:
  push:
    branches: ["cicsts/v5.5"]
  pull_request:
    branches: ["cicsts/v5.5"]

jobs:
  build-maven:
    name: Build Maven

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11, 17, 21]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: "semeru"
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots --file pom.xml -Djava.version=${{ matrix.jdk }} package
      - run: |
             mkdir staging 
             cp cics-java-osgi-link-app/target/*.jar staging
             cp cics-java-osgi-link-bundle/target/*.zip staging
      - uses: actions/upload-artifact@v4
        with:
          name: cics-java-osgi-link (Maven, Java ${{ matrix.jdk }})
          path: staging

  build-gradle:
    name: Build Gradle
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [8, 11, 17, 21]
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'semeru'
    - uses: gradle/actions/setup-gradle@v3
      with: 
        gradle-version: 8.5
    - name: Build with Gradle
      run: gradle build -Pjava_version=${{ matrix.jdk }}
